### PR TITLE
Added support for Pipelines

### PR DESCRIPTION
**Pull request by tisoft**
Implemented SimpleBuildStep to support the Jenkins pipelines.

### CODE REVIEW

**Comment by jawebada** [comment]
I'd appreciate if this pull request could be reviewed. We are currently porting our Jenkins jobs to Jenkinsfiles and missing support for sonar-gerrit is the remaining issue we are facing. Thanks.

**Comment by adidik** [comment]
Working on it, guys. Will be introduced soon.

**Comment by bzon** [comment]
@adidik How near are we at releasing this awesome feature?

**Comment by rajesh-kumar** [comment]
@adidik Really looking forward to this pipeline support.

**Comment by tisoft** [comment]
Rebased to latest master.

**Comment by aquarellian** [comment]
@tisoft thank you for your contribution, I really appreciate it!

Could you please send me your jenkins job configuration? I am experiencing problems with testing your change: the environmental variables (GERRIT_CHANGE_NUMBER and GERRIT_PATCHSET_NUMBER), necessary for work of the plugin, are not being passed to it, though they are available in the script and correct build is being run. Really stuck on it.

My script looks like:
 // code from gerrit-trigger manual
  git url: 'ssh:<my gerrit repo url>'
  // Fetch the changeset to a local branch using the build parameters provided to the
  // build by the Gerrit plugin...
  **def changeBranch = "change-${GERRIT_CHANGE_NUMBER}-${GERRIT_PATCHSET_NUMBER}"
  sh "git fetch origin ${GERRIT_REFSPEC}:${changeBranch}"
  sh "git checkout ${changeBranch}"**
  //... mvn clean install sonar:sonar etc ...
  stage 'Sonar-Verify'
  step([$class: 'SonarToGerritPublisher', category: 'Sonar-Verify', changedLinesOnly: true, ...)

**Comment by tisoft** [comment]
This is the relevant portions from our jenkinsfile:

```
checkout([$class: 'GitSCM', branches: [[name: '$GERRIT_BRANCH']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'CloneOption', depth: 0, noTags: false, reference: '', shallow: true], [$class: 'BuildChooserSetting', buildChooser: [$class: 'GerritTriggerBuildChooser']]], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '2f7c4616-5be1-46b3-8645-06c0641c7673', refspec: '$GERRIT_REFSPEC', url: 'ssh://XXX@YYY:29418/ZZZ']]])

//... compile and run sonar

step([$class: 'SonarToGerritPublisher', category: 'Code-Review', postScore: true, newIssuesOnly: true, changedLinesOnly: false, noIssuesScore: '+1', issuesScore: '-1', sonarURL: 'http://XXX/sonar', subJobConfigs: [[sonarReportPath: "${env.WORKSPACE}/target/sonar/sonar-report.json"]]])
    
 ```

Maybe the reason it is working for me is the GerritTriggerBuildChooser?

**Comment by aquarellian** [comment]
@tisoft Thank you for the answer. GerritTriggerBuildChooser doesn't make any difference. 

The reason is the difference in versions of jenkins core used. You haven't change jenkins minimum requirements, so you probably didn't run jenkins in debug mode, but created an hpi to check your changes on your existing jenkins installation. That's why it is working for you. I am using an older version of Jenkins to make sure that conservative users are supported, and my version of jenkins don't contain a fix for this situation - JENKINS-30910.

I'll include a fix for this, the explanations above are just FYI.

**Comment by tisoft** [comment]
You are right. I tested on our production Jenkins instance. Thanks for looking into it. 👍

**Comment by t0klian** [comment]
Was it merged into?

**Comment by tisoft** [comment]
It was merged as part of #19.

**Pull request closed without merging**
